version: '3.8'

services:
  shopify-cron:
    build: .
    container_name: shopify-cron-job
    restart: unless-stopped
    environment:
      # FTP Configuration
      - FTP_HOST=${FTP_HOST:-ftp.qgold.com}
      - FTP_PORT=${FTP_PORT:-21}
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      
      # Shopify Configuration
      - SHOPIFY_STORE_URL=${SHOPIFY_STORE_URL}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      
      # Shopify Processing Settings
      - SHOPIFY_BATCH_SIZE=${SHOPIFY_BATCH_SIZE:-20}
      - SHOPIFY_BATCH_DELAY=${SHOPIFY_BATCH_DELAY:-1000}
      - SHOPIFY_DRY_RUN=${SHOPIFY_DRY_RUN:-false}
      - SHOPIFY_PARALLEL_BATCH=${SHOPIFY_PARALLEL_BATCH:-true}
      - SHOPIFY_ENABLE_UPDATES=${SHOPIFY_ENABLE_UPDATES:-true}
      
      # Cron Configuration
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 2 * * *}
      - TIMEZONE=${TIMEZONE:-UTC}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # File Processing Configuration
      - DOWNLOAD_DIR=/app/downloads
      - KEEP_FILES_DAYS=${KEEP_FILES_DAYS:-7}
      
      # Health Check Configuration
      - HEALTH_CHECK_PORT=3002
      
      # Environment
      - NODE_ENV=${NODE_ENV:-production}
    
    ports:
      - "3002:3002"  # Health check port
    
    volumes:
      - shopify_logs:/app/logs
      - shopify_downloads:/app/downloads
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  shopify_logs:
    driver: local
  shopify_downloads:
    driver: local

networks:
  default:
    name: shopify-network
